# Generated by Django 4.2.3 on 2023-08-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InscriptionAnnuelle",
            fields=[
                (
                    "idInscription",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("year", models.IntegerField()),
                ("state", models.IntegerField()),
                ("mention", models.CharField(max_length=255, null=True)),
                ("plusInfos", models.CharField(max_length=255, null=True)),
                ("rank", models.IntegerField()),
                ("type", models.CharField(max_length=255, null=True)),
                ("validation", models.CharField(max_length=255, null=True)),
                (
                    "idLevel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.level",
                    ),
                ),
                (
                    "idStudent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Accounts.student",
                    ),
                ),
            ],
            options={
                "db_table": "inscriptionannuelle",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InscriptionModule",
            fields=[
                (
                    "idInscriptionModule",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("noteFinale", models.FloatField(default=-1)),
                ("noteSN", models.FloatField(default=-1)),
                ("noteSR", models.FloatField(default=-1)),
                ("plusInfos", models.CharField(max_length=255, null=True)),
                ("validation", models.CharField(max_length=255, null=True)),
                (
                    "idInscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscriptions.inscriptionannuelle",
                    ),
                ),
                (
                    "idModule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "db_table": "inscriptionmodule",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="InscriptionMatiere",
            fields=[
                (
                    "idInscriptionMatiere",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("coefficient", models.FloatField()),
                ("noteFinale", models.FloatField(default=-1)),
                ("noteSN", models.FloatField(default=-1)),
                ("noteSR", models.FloatField(default=-1)),
                ("plusInfos", models.CharField(max_length=255, null=True)),
                ("validation", models.CharField(max_length=255, null=True)),
                (
                    "idInscription",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inscriptions.inscriptionannuelle",
                    ),
                ),
                (
                    "idMatiere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.element",
                    ),
                ),
            ],
            options={
                "db_table": "inscriptionmatiere",
                "managed": True,
            },
        ),
    ]
