# Generated by Django 4.2.3 on 2023-08-18 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="course_pdfs/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Filiere",
            fields=[
                ("idFiliere", models.BigAutoField(primary_key=True, serialize=False)),
                ("anneeFinaccreditation", models.IntegerField()),
                ("anneeaccreditation", models.IntegerField()),
                ("codeFiliere", models.CharField(max_length=255, null=True)),
                ("titleFiliere", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "Filiere",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Level",
            fields=[
                ("idLevel", models.BigAutoField(primary_key=True, serialize=False)),
                ("alias", models.CharField(max_length=255, null=True)),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "idFiliere",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.filiere",
                    ),
                ),
                (
                    "idNextLevel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="courses.level",
                    ),
                ),
            ],
            options={
                "db_table": "Level",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                ("idModule", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255, null=True)),
                ("title", models.CharField(max_length=255, null=True)),
                (
                    "idNiveau",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.level"
                    ),
                ),
            ],
            options={
                "db_table": "Module",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                ("idMatiere", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=255, null=True)),
                ("currentCoefficient", models.FloatField(default=1.0)),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "idModule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.module",
                    ),
                ),
            ],
            options={
                "db_table": "Element",
                "managed": True,
            },
        ),
    ]
