# Generated by Django 4.2.3 on 2023-08-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_filiere_course_level_course_module_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("pdf", models.FileField(upload_to="news_pdfs/")),
            ],
            options={
                "db_table": "News",
                "managed": True,
            },
        ),
    ]
